### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by strugee** [straticjs/RFCs#35]
Stratic is getting mature enough that it's time to start pushing towards a 1.0 release. Here's what I think we _have_ to do before that can happen.

**General**:

- [ ] Decide on a logo, #22
- [ ] Move to gulp 4, #34
- [ ]  Policy on pulling modules into the straticjs org, #21 

**Website**:

- [ ] Blog needs to be enabled, straticjs/stratic.github.io#2
- [ ] Put the logo on there somewhere, straticjs/stratic.github.io#3

**Documentation**:

- [ ] Project-wide design documentation, straticjs/stratic.github.io#1
- [ ] At minimum, an index of available modules/what modules to use for different tasks, straticjs/stratic.github.io#2
- [ ]  Document #stratic, #19 
- [ ] generator-stratic README is awful, straticjs/generator-stratic#23
- [ ] Finish static to Stratic

**Miscellaneous cleanups**:

- [x] I don't go by Alex anymore so make sure everything says AJ, #31 
- [x] Make sure package.json repository metadata is correct, #32 
- [x]  Ensure READMEs don't reference Stratic header parsing, #25 
- [ ] Consistently use PluginErrors everywhere, #23
- [ ] Support NODE_DEBUG, #4 

We may want to do #14 too, before we get too many users? We might want to do straticjs/generator-stratic#16 and straticjs/generator-stratic#15 too, I'm not sure.

**Comment by strugee** [comment]
Ref #11 for when we're done!
